SAVE_PATH = "./model/bert.pth"
MLM_PATH = "./model/mlm.hf"
TKN_NAME = "bert-base-uncased"
DS_NAME = "bookcorpus"

SENTENCE_LEN = 64
BATCH_SIZE=4
LAYERS=4
ATTN_HEADS=4
EMBED_DEPTH=768
HIDDEN_DEPTH=1024
DROPOUT=.25

EPOCHS = 200
